/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication20;

/**
 *
 * @author klimaco
 */
public class Form extends javax.swing.JFrame {

    private PrevisaoFuzzy fuzzySystem;
    private java.util.HashMap<String, double[]> month;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        
        
		month = new java.util.HashMap<String, double[]>();

		// 2011 Entries
		month.put("Jan/2011", new double[] {-18.91, 0.27, 7.54, -1.37, -2.37, -5.39, -0.08, 2.12, 0.79, 2.8, 2.13, 29.73});
		month.put("Fev/2011", new double[] {0.27, 7.54, -1.37, -2.37, -5.39, -0.08, 2.12, 0.79, 2.8, 2.13, 29.73, -20.49});
		month.put("Mar/2011", new double[] {7.54, -1.37, -2.37, -5.39, -0.08, 2.12, 0.79, 2.8, 2.13, 29.73, -20.49, -6.35});
		month.put("Abr/2011", new double[] {-1.37, -2.37, -5.39, -0.08, 2.12, 0.79, 2.8, 2.13, 29.73, -20.49, -6.35, 10.14});
		month.put("Mai/2011", new double[] {-2.37, -5.39, -0.08, 2.12, 0.79, 2.8, 2.13, 29.73, -20.49, -6.35, 10.14, 8.0});
		month.put("Jun/2011", new double[] {-5.39, -0.08, 2.12, 0.79, 2.8, 2.13, 29.73, -20.49, -6.35, 10.14, 8.0, -10.92});
		month.put("Jul/2011", new double[] {-0.08, 2.12, 0.79, 2.8, 2.13, 29.73, -20.49, -6.35, 10.14, 8.0, -10.92, -2.49});
		month.put("Ago/2011", new double[] {2.12, 0.79, 2.8, 2.13, 29.73, -20.49, -6.35, 10.14, 8.0, -10.92, -2.49, 6.41});
		month.put("Set/2011", new double[] {0.79, 2.8, 2.13, 29.73, -20.49, -6.35, 10.14, 8.0, -10.92, -2.49, 6.41, -1.84});
		month.put("Out/2011", new double[] {2.8, 2.13, 29.73, -20.49, -6.35, 10.14, 8.0, -10.92, -2.49, 6.41, -1.84, -0.22});
		month.put("Nov/2011", new double[] {2.13, 29.73, -20.49, -6.35, 10.14, 8.0, -10.92, -2.49, 6.41, -1.84, -0.22, 5.16});
		month.put("Dez/2011", new double[] {29.73, -20.49, -6.35, 10.14, 8.0, -10.92, -2.49, 6.41, -1.84, -0.22, 5.16, -1.84});

		// 2012 Entries
		month.put("Jan/2012", new double[] {-20.49, -6.35, 10.14, 8.0, -10.92, -2.49, 6.41, -1.84, -0.22, 5.16, -1.84, 30.66});
		month.put("Fev/2012", new double[] {-6.35, 10.14, 8.0, -10.92, -2.49, 6.41, -1.84, -0.22, 5.16, -1.84, 30.66, -18.91});
		month.put("Mar/2012", new double[] {10.14, 8.0, -10.92, -2.49, 6.41, -1.84, -0.22, 5.16, -1.84, 30.66, -18.91, 0.27});
		month.put("Abr/2012", new double[] {8.0, -10.92, -2.49, 6.41, -1.84, -0.22, 5.16, -1.84, 30.66, -18.91, 0.27, 7.54});
		month.put("Mai/2012", new double[] {-10.92, -2.49, 6.41, -1.84, -0.22, 5.16, -1.84, 30.66, -18.91, 0.27, 7.54, -1.37});
		month.put("Jun/2012", new double[] {-2.49, 6.41, -1.84, -0.22, 5.16, -1.84, 30.66, -18.91, 0.27, 7.54, -1.37, -2.37});
		month.put("Jul/2012", new double[] {6.41, -1.84, -0.22, 5.16, -1.84, 30.66, -18.91, 0.27, 7.54, -1.37, -2.37, -5.39});
		month.put("Ago/2012", new double[] {-1.84, -0.22, 5.16, -1.84, 30.66, -18.91, 0.27, 7.54, -1.37, -2.37, -5.39, -0.08});
		month.put("Set/2012", new double[] {-0.22, 5.16, -1.84, 30.66, -18.91, 0.27, 7.54, -1.37, -2.37, -5.39, -0.08, 2.12});
		month.put("Out/2012", new double[] {5.16, -1.84, 30.66, -18.91, 0.27, 7.54, -1.37, -2.37, -5.39, -0.08, 2.12, 0.79});
		month.put("Nov/2012", new double[] {-1.84, 30.66, -18.91, 0.27, 7.54, -1.37, -2.37, -5.39, -0.08, 2.12, 0.79, 2.8});
		month.put("Dez/2012", new double[] {30.66, -18.91, 0.27, 7.54, -1.37, -2.37, -5.39, -0.08, 2.12, 0.79, 2.8, 2.13});
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("gerar regras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("prever");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double[] inputs = {-27.75, 1.47, 4.29, 6.51, -4.22, -2.79, 7.76, -1.24, -1.45, 7.99, -3.24, 36.31, -25.97, -4.22, 16.09, -8.23, -0.35, -3.85, 6.63, -3.3, -2.1, 7.13, -3.01, 35.6, -25.38, -3.99, 6.14, 5.23, -8.54, -2.07, 4.78, -1.12, 1.12, 2.32, 1.18, 31.79, -23.29, -2.41, 10.79, -0.77, -4.51, -0.9, 1.56, 2.37, 0.47, 1.63, 1.88, 33.56, -22.84, -2.35, 16.76, -12.13, 8.66, -5.65, 4.4, 3.57, -5.45, 7.22, 1.19, 27.86, -22.59, -4.12, 6.68, 7.2, -3.67, -5.25, 5.92, 0.95, -3.77, 8.33, -2.24, 31.68, -20.96, -5.54, 10.74, -3.28, 0.46, -4.59, 4.21, -1.37, -0.11, 7.82, -4.43, 34.71};

		// Setting domain with security margin
		double marginMin = -34.16; //inputs.Min() + ((double.Parse(textBox2.Text) / 100.0) * inputs.Min());
		double marginMax = 42.72; //inputs.Max() + ((double.Parse(textBox2.Text) / 100.0) * inputs.Max());
		System.out.println("[ " + marginMax + ", " + marginMin + " ]");
		// Sets
		Conjunto[] sets = new Conjunto[5];

		// Determining sets
		double sizeOfSet = (marginMax - marginMin) / (sets.length - 1); // 2*N + 1
		sets[0] = new Conjunto("set0", marginMin - sizeOfSet, marginMin, marginMin + sizeOfSet);
		for (int i = 1; i < sets.length; i++) {
			sets[i] = new Conjunto("set" + i, sets[i - 1].getPeak(), sets[i - 1].getEnd(), sets[i - 1].getEnd() + sizeOfSet);
			}

		// Getting the base of rules
		Mendel algorithm = new Mendel(inputs, sets);

		// Initializing the fuzzy system
		fuzzySystem = new PrevisaoFuzzy(sets, algorithm.getRegras());
                String richTextBox1="";
		for (int i = 0; i < algorithm.getRegras().size(); i++) {
			richTextBox1 += (i + 1) + ") " + algorithm.getRegras().get(i).toString() + "\n\n";
			}
                
                System.out.println(richTextBox1);
                
               

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //System.out.println("Jan/2012 = " + fuzzySystem.doIt(month.get("Jan/2012")));
         //System.out.println("Fev/2011 = " + fuzzySystem.doIt(month.get("Fev/2011")));
         //System.out.println("Mar/2012 = " + fuzzySystem.doIt(month.get("Mar/2012")));
        //System.out.println("Abr/2011 = " + fuzzySystem.doIt(month.get("Abr/2011")));
        //System.out.println("Mai/2011 = " + fuzzySystem.doIt(month.get("Mai/2011")));
        System.out.println("Jun/2011 = " + fuzzySystem.doIt(month.get("Jun/2011")));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Conjunto the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
